eosmkdir='eos root://cmseos.fnal.gov mkdir'

$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_looseCRe3e1/ 
