eosmkdir='eos root://cmseos.fnal.gov mkdir' 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_looseCRe3e1/ 
