eosmkdir='eos root://cmseos.fnal.gov mkdir'

$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_tight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRge2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRge2ge0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe3ge2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRge4e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe3e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe2e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe2e0/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe2e2/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_looseCRe3e1/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_looseCRe3e1/ 
