isMC=999
isData=1

from ROOT import *

samples = {"TTGamma"   : [["TTGamma_SingleLept_2016_AnalysisNtuple.root",
                           "TTGamma_Dilepton_2016_AnalysisNtuple.root",
                           "TTGamma_Hadronic_2016_AnalysisNtuple.root",
                           ],
                          kOrange,#kAzure+7,
                          "t#bar{t}+#gamma",
                          isMC
                          ],
           "TTGJets"   : [["TTGJets_AnalysisNtuple.root",
                           ],
                          kOrange,#kAzure+7,
                          "t#bar{t}+#gamma",
                          isMC
                          ],
           "TTbar"     : [["TTbarPowheg_Semilept_2016_AnalysisNtuple_1of5.root",
                           "TTbarPowheg_Semilept_2016_AnalysisNtuple_2of5.root",
                           "TTbarPowheg_Semilept_2016_AnalysisNtuple_3of5.root",
                           "TTbarPowheg_Semilept_2016_AnalysisNtuple_4of5.root",
                           "TTbarPowheg_Semilept_2016_AnalysisNtuple_5of5.root"
                           ],
                          kRed+1,
                          "t#bar{t}",
                          isMC
                          ],
           "TGJets"    :[["TGJets_2016_AnalysisNtuple.root",
                          ],
                         kGray,
                         "t+#gamma",
                         isMC
                         ],
           "WJets"     : [["W1jets_2016_AnalysisNtuple.root",
                           "W2jets_2016_AnalysisNtuple.root",
                           "W3jets_2016_AnalysisNtuple.root",
                           "W4jets_2016_AnalysisNtuple.root",
                           ],
                          kCyan-3,
                          "W+jets",
                          isMC
                          ],
           "WJetsInclusive"     : [["WjetsInclusive1_AnalysisNtuple.root",
                                    "WjetsInclusive2_AnalysisNtuple.root",
                                    "WjetsInclusive3_AnalysisNtuple.root",
                                    "WjetsInclusive4_AnalysisNtuple.root",
                                    "WjetsInclusive5_AnalysisNtuple.root",
                                    "WjetsInclusive6_AnalysisNtuple.root",
                           ],
                          kCyan-3,
                          "W+jets",
                          isMC
                          ],
           "ZJets"     : [["DYjetsM10to50_2016_AnalysisNtuple.root",#"DYjetsM10to50_MLM_AnalysisNtuple.root",
                           "DYjetsM50_2016_AnalysisNtuple_1of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_2of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_3of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_4of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_5of5.root",
                           ],
                          kCyan-5,
                          "Z+jets",
                          isMC
                          ],



	   "ZJets_NLO" : [["DYjetsM10to50_2016_AnalysisNtuple.root",#"DYjetsM10to50_MLM_AnalysisNtuple.root",
                           "DYjetsM50_2016_AnalysisNtuple_1of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_2of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_3of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_4of5.root",
                           "DYjetsM50_2016_AnalysisNtuple_5of5.root",
                           ],
                          kCyan-5,
                          "Z+jets",
                          isMC
                          ],

           "WGamma"    : [["WGamma_01J_5f_2016_AnalysisNtuple.root",
                           ],
                          kBlue-4,
                          "W+#gamma",
                          isMC
                          ],
           "ZGamma"    : [["ZGamma_01J_5f_LoosePt_2016_AnalysisNtuple.root", "ZGamma_01J_5f_lowMass_2016_AnalysisNtuple.root",
                           ],
                          kBlue-2,
                          "Z+#gamma",
                          isMC
                          ],
           "Diboson"   : [["WW_2016_AnalysisNtuple.root",
                           "WZ_2016_AnalysisNtuple.root",
                           "ZZ_2016_AnalysisNtuple.root",
                           ],
                          kCyan-7,
                          "WW/WZ/ZZ",
                          isMC
                          ],
           "SingleTop" : [["ST_s_channel_2016_AnalysisNtuple.root",
                           "ST_t_channel_2016_AnalysisNtuple.root",
                           "ST_tW_channel_2016_AnalysisNtuple.root",
                           "ST_tbar_channel_2016_AnalysisNtuple.root",
                           "ST_tbarW_channel_2016_AnalysisNtuple.root",
                           ],
                          kOrange-3,
                          "Single top",
                          isMC
                          ],
           "ST-tch" : [["ST_t-channel_2016_AnalysisNtuple.root",
                        "ST_tbar-channel_2016_AnalysisNtuple.root",
                        ],
                       kOrange-3,
                       "Single top (t-ch.)",
                       isMC
                       ],
           "ST-sch" : [["ST_s-channel_2016_AnalysisNtuple.root",
                        ],
                       kOrange-4,
                       "Single top (s-ch.)",
                       isMC
                       ],
           "ST-tW" : [["ST_tW-channel_2016_AnalysisNtuple.root",
                        "ST_tbarW-channel_2016_AnalysisNtuple.root",
                        ],
                       kOrange-5,
                       "Single top (tW)",
                       isMC
                       ],
           "TTV"       : [["TTWtoQQ_2016_AnalysisNtuple.root",
                           "TTWtoLNu_2016_AnalysisNtuple.root",
                           "TTZtoLL_2016_AnalysisNtuple.root",
                           ],
                          kRed-7,
                          "ttV",
                          isMC
                          ],
           "QCDEle"    : [["QCD_Pt20to30_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt30to50_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt50to80_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt80to120_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt120to170_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt170to300_Ele_2016_AnalysisNtuple.root",
                           "QCD_Pt300toInf_Ele_2016_AnalysisNtuple.root",
                           ],
                          kGreen+3,
                          "QCD",
                          isMC
                          ],

           "QCDMu"    : [["QCD_Pt20to30_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt30to50_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt50to80_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt80to120_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt120to170_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt170to300_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt300to470_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt470to600_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt600to800_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt800to1000_Mu_2016_AnalysisNtuple.root",
                          "QCD_Pt1000toInf_Mu_2016_AnalysisNtuple.root",
                          ],
                         kGreen+3,
                         "QCD",
                         isMC
                         ],
           "GJets"     : [["GJets_HT40To100_2016_AnalysisNtuple.root",
                           "GJets_HT100To200_2016_AnalysisNtuple.root",
                           "GJets_HT200To400_2016_AnalysisNtuple.root",
                           "GJets_HT400To600_2016_AnalysisNtuple.root",
                           "GJets_HT600ToInf_2016_AnalysisNtuple.root",
                           ],
                          kGreen+3,
                          "#gamma+jets",
                          isMC
                          ],
           "DataMu"    : [["Data_SingleMu_b_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_b_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_b_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_b_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_b_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_c_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_c_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_c_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_c_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_c_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_d_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_d_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_d_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_d_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_d_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_e_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_e_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_e_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_e_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_e_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_f_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_f_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_f_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_f_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_f_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_g_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_g_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_g_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_g_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_g_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleMu_h_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleMu_h_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleMu_h_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleMu_h_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleMu_h_2016_AnalysisNtuple_5of5.root"
                           ],
                          kBlack,
                          "Data",
                          isData
                          ],
           "DataEle"   : [["Data_SingleEle_b_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_b_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_b_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_b_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_b_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_c_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_c_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_c_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_c_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_c_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_d_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_d_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_d_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_d_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_d_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_e_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_e_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_e_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_e_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_e_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_f_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_f_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_f_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_f_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_f_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_g_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_g_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_g_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_g_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_g_2016_AnalysisNtuple_5of5.root",
                           "Data_SingleEle_h_2016_AnalysisNtuple_1of5.root",
                           "Data_SingleEle_h_2016_AnalysisNtuple_2of5.root",
                           "Data_SingleEle_h_2016_AnalysisNtuple_3of5.root",
                           "Data_SingleEle_h_2016_AnalysisNtuple_4of5.root",
                           "Data_SingleEle_h_2016_AnalysisNtuple_5of5.root"
                           ],
                          kBlack,
                          "Data",
                          isData
                          ],
           }



# List that is the same as the keys of samples, but given in the order we want to draw
sampleList = ["TTGamma",
              "TTbar",
              "TGJets",
              "SingleTop",
              "WJets",
              "ZJets",
              #"ZJets_NLO",
              "WGamma",
              "ZGamma",
              "Diboson",
              "TTV",
              "GJets",
              "QCD",
              "Data",
              ]



